

http://localhost:8090/v1/users/customer

###

http://localhost:8090/v1/users/customer/1

###

POST http://localhost:8090/v1/users/customer HTTP/1.1
Content-Type: application/json

{
    "username": "gabi",
    "firstName": "Gabriela",
    "lastName": "Dantas",
    "document": "04881472544",
    "email": "gabrieladantass@gmail.com"
}

###

DELETE http://localhost:8090/v1/users/customer/2 HTTP/1.1